spring.application.name=PawConnect
server.port=8080

# H2 Database Config for local testing
spring.datasource.url=jdbc:h2:mem:pawconnectdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# Hibernate Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Thymeleaf Config
spring.thymeleaf.cache=false
